### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [osenvosem/music-player-app#1]
Hi @osenvosem . I'm graphic disigner. I would like to know if you are interested that I make a logo for your project? If you allowed me, i"ll make logo for your project.

**Comment by osenvosem** [comment]
Thank you for your offer @mirzazulfan, but, firstly, this is just a demo app and secondly, I'm also a graphic designer, I would made it myself if I needed to. Good luck. 🙂

**Comment by mirzazulfan** [comment]
Ohh.. it's ok. :) .. good luck
